// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egqinbmbyxpuxlwrrtag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncWluYm1ieXhwdXhsd3JydGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTkwODUsImV4cCI6MjA2NDc3NTA4NX0.3I2qhFrK268_ApRekglqL06WIykjYnDNfRe3FlTqkMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);